### ISSUE TITLE
bh fails to compile wit gambit 4.8.0 from git under Arch Linux

### ISSUE THREAD

**Issue by stefanhusmann** [pereckerdal/blackhole#52]
I try to package blackhole-git und Arch Linux 64 bit
This happens:

==> Making package: blackhole-git 0.2.4.g50bb6fd-1 (Wed Sep 30 21:19:46 CEST 2015)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating blackhole git repo...
Fetching origin
==> Validating source files with md5sums...
    blackhole ... Skipped
==> Extracting sources...
  -> Creating working copy of blackhole git repo...
Reset branch 'makepkg'
==> Starting pkgver()...
==> Starting prepare()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
bh.scm:
*** ERROR -- missing or invalid linking information for module "/usr/lib/gambit-c//_gambcgsc"
gcc: error: bh_.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
*** ERROR IN ##main -- C compilation or link failed while compiling "bh_.c"
==> Entering fakeroot environment...
==> Starting package()...
install: cannot stat 'bh': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...

Process makepkg exited abnormally with code 2

The compile.sh is modyfied, because gsc is a ghostscript binary on Arch Linux.
``` script
#!/bin/sh
GAMBCLIBDIR="`gambitc -e \"(display (path-expand \\\"~~lib\\\"))\"`"
echo "bh.scm:" && gambitc -link -l "$GAMBCLIBDIR/_gambcgsc" bh.scm && gambitc -obj bh_.c bh.c && gambitc -exe -ld-options "$GAMBCLIBDIR/libgambcgsc.a" bh_.o bh.o
rm -f bh_.o bh_.c bh.c bh.o
```

**Comment by stefanhusmann** [comment]
sorry for the noise, I only had to change gambc to gambit, and all went well.

**Comment by pereckerdal** [comment]
Sorry for not responding. Closing this since it seems like you've managed to get it to work
